apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vanity
  namespace: friend-__NAME__
spec:
  entryPoints: [websecure]
  routes:
    - match: Host(`__HOST__`)
      kind: Rule
      middlewares:
        - name: friend-basic
          namespace: friend-__NAME__
      services:
        - name: ttyd
          port: 7681
  tls:
    certResolver: cfresolver
