apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: friend-data
  namespace: friend-cyprien-iov
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
